feat: add metrics resource
statuspal/terraform-provider-statuspal pull request #25
Opened 2024-11-20 15:45 UTC by henrybarreto

2024-11-20 15:46 UTC, henrybarreto commented
Unfortunately, I still didn't test against the real API.

2024-11-21 11:13 UTC, FabianDaniel00 requested changes

2024-11-21 11:13 UTC, FabianDaniel00 commented on internal/provider/metric_resource.go
> +			},
Look at for example the service resource.
We have the `status_page_subdomain` and `id` at the top level and we have a `service` `SingleNestedAttribute`.
Please follow that format.
https://github.com/statuspal/terraform-provider-statuspal/blob/main/internal/provider/service_resource.go#L117-L126

2024-11-21 11:13 UTC, FabianDaniel00 commented on internal/provider/metric_resource.go
> +	}
Why we need these checks, since these attributes are set as required in the schema?

2024-11-21 11:13 UTC, FabianDaniel00 commented on internal/provider/metric_resource.go
> +	data.IntegrationID = types.StringValue(metric.IntegrationID)
Can we use "mapper" functions here to minimize the code duplication.
See the service resource:
https://github.com/statuspal/terraform-provider-statuspal/blob/e1c48870df86da38c85828e706c1cf784ce1cb62/internal/provider/service_resource.go#L399
https://github.com/statuspal/terraform-provider-statuspal/blob/e1c48870df86da38c85828e706c1cf784ce1cb62/internal/provider/service_resource.go#L416

2024-11-21 11:17 UTC, FabianDaniel00 commented
> Unfortunately, I still didn't test against the real API.

Were you able to setup [`statushq`](https://github.com/statuspal/statushq) locally?

2024-11-21 16:06 UTC, henrybarreto commented
> > Unfortunately, I still didn't test against the real API.
> 
> Were you able to setup [`statushq`](https://github.com/statuspal/statushq) locally?

Unfortunately, I don't have access to this repository.

2024-11-21 23:59 UTC, henrybarreto commented
I've tested it. @FabianDaniel00, could please double-check it?

2024-11-22 12:00 UTC, FabianDaniel00 requested changes
I forgot to mention, we need to add the metrics data source also.

2024-11-22 17:58 UTC, FabianDaniel00 approved these changes

2024-11-22 17:58 UTC, merged