feat: add metric and metrics data source
statuspal/terraform-provider-statuspal pull request #27
Opened 2024-11-23 03:23 UTC by henrybarreto

2024-11-25 11:47 UTC, FabianDaniel00 requested changes
Please fix these small things with examples:

- Add one `main.tf` to `examples/metric` folder and delete the others. Take a look to other resources.
- Add examples to `examples/data-sources/statuspal_metrics/data-source.tf` file.
- Add examples to `examples/resources/statuspal_metric/import.tf` and `examples/resources/statuspal_metric/resource.tf` files.

2024-11-25 11:47 UTC, FabianDaniel00 commented on internal/provider/metric_data_source.go
We don't need data source for only 1 metric since there is the `import` feature.
https://github.com/statuspal/terraform-provider-statuspal/blob/main/internal/provider/metric_resource.go#L287-L289

Also I noticed this import feature is not finished. Please take a look how I did the service import: https://github.com/statuspal/terraform-provider-statuspal/blob/main/internal/provider/service_resource.go#L536-L555

2024-11-25 11:47 UTC, FabianDaniel00 commented on internal/provider/metrics_data_resource_test.go
Please rename this file to: `metrics_data_source_test.go`

2024-11-25 15:46 UTC, henrybarreto commented
Changes requested done.

2024-11-26 12:50 UTC, FabianDaniel00 requested changes
Looking great, just a small thing

2024-11-26 12:50 UTC, FabianDaniel00 commented on internal/provider/metric_resource.go
> +	resource.ImportStatePassthroughID(ctx, path.Root("service").AtName("id"), req, resp)
```suggestion
	resource.ImportStatePassthroughID(ctx, path.Root("metric").AtName("id"), req, resp)
```

2024-11-26 17:46 UTC, merged